### ISSUE TITLE
[simple_use_case] expose mesh resolution as parameter

### ISSUE THREAD

**Issue by dglaeser** [BAMresearch/NFDI4IngScientificWorkflowRequirements#26]
We should expose an integral (or floating point) parameter to the workflow to be able to run meaningful different realizations of the workflow.

TODO:
- [ ] add parameter to .geo file (with default)
- [ ] add that parameter to "make-mesh" job
- [ ] (maybe) remove useless parameters (e.g. dolfinscript in cwl? The dolfin module should be specific to this one simulation, no?)

**Comment by joergfunger** [comment]
I realized that it would additionally be interesting to have a parameter as output (not a file). Do we have a meaningful example for that?

**Comment by dglaeser** [comment]
not out-of-the-box I think. We could make the domain dimensions an output of the mesh generation step maybe, and then use the dimensions to scale our simulation. For instance, scale the boundary condition value with the domain size.. In this case our dolfin script would also receive an additional non-file input parameter.

**Comment by joergfunger** [comment]
We don't even have to scale the boundary condition. We would need this information already to select the appropriate boundary nodes. @pdiercks What do you think? That would require a slight modification of our input file to prescribe Dirichlet boundary onfitions e.g. only on the righthand side (thus we would have to know the size of the structure from the meshfile.

```
def boundary(x, on_boundary):
    if on_boundary:
        if near(x[0], 0, tol) or near(x[0], lengthAsInput, tol):
            return True
        else:
            return False
    else:
        return False
return on_boundary
```

**Comment by pdiercks** [comment]
I think either way is fine, but scaling the boundary condition value seems less intrusive to me (than changing the Dirichlet boundary).

**Comment by pdiercks** [comment]
I thought about how one could return some parameter from the mesh generation step. Maybe using the python API of gmsh is the simplest way of doing this?
For example one could have a function which writes the `msh` file and also returns the desired parameters.
```python
def generate_rectangle_mesh():
    """
    Partition of a rectangle Ω = [a, b] x [a, b]
    into (nx - 1) * (ny - 1) triangles


     ^  4---------3
     |  |         |
     b  |    Ω    |
     |  |         |
     v  1---------2
        <----a---->
    """
    import gmsh

    # Parameters
    nx = 5
    ny = 5
    x1, y1 = 0.0, 0.0
    x3 = 2.0
    y3 = 3.0
    a = x3 - x1
    b = y3 - y1

    gmsh.initialize()
    # add model name
    gmsh.model.add("rectangle")

    # add all four points
    gmsh.model.geo.addPoint(x1, y1, 0.0)
    gmsh.model.geo.addPoint(x1 + a, y1, 0.0)
    gmsh.model.geo.addPoint(x1 + a, y1 + b, 0.0)
    gmsh.model.geo.addPoint(x1, y1 + b, 0.0)

    # add lines in counter-clock wise order
    gmsh.model.geo.addLine(1, 2, 1)
    gmsh.model.geo.addLine(2, 3, 2)
    gmsh.model.geo.addLine(3, 4, 3)
    gmsh.model.geo.addLine(4, 1, 4)

    # add curve loop and surface
    gmsh.model.geo.addCurveLoop([1, 2, 3, 4], 1)
    gmsh.model.geo.addPlaneSurface([1], 1)

    gmsh.model.geo.synchronize()

    # add physical group
    ps = gmsh.model.addPhysicalGroup(2, [1])
    gmsh.model.setPhysicalName(2, ps, "surface")

    # generate 2d mesh
    gmsh.model.mesh.generate(2)

    # write output file
    gmsh.write("rectangle.msh")
    gmsh.finalize()

    return (a, b)

```
With `pydiot` one could then use [getargs](https://pydoit.org/dependencies.html#getargs) to use the computed values in another task.
```python
def task_generate_mesh():
    """generate mesh and output some parameter"""

    def generate_mesh():
        from rectangle import generate_rectangle_mesh
        a, b = generate_rectangle_mesh()
        return {"x": a, "y": b}

    return {
            "actions": [(generate_mesh, []), ],
            "targets": ["rectangle.msh"],
            "clean": True,
            }


def task_use_python():
    """use python to show getargs"""
    return {'actions': [show_getargs],
            'getargs': {'x': ('generate_mesh', 'x'),
                        'y': ('generate_mesh', 'y')},
            'verbosity': 2,
            }

def show_getargs(x, y):
   print("this is x: {}".format(x))
   print("this is y: {}".format(y))
```
Running `doit` would give the following output:
```
.  generate_mesh
Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Line)
Info    : [ 30%] Meshing curve 2 (Line)
Info    : [ 50%] Meshing curve 3 (Line)
Info    : [ 80%] Meshing curve 4 (Line)
Info    : Done meshing 1D (Wall 0.000712042s, CPU 0.003428s)
Info    : Meshing 2D...
Info    : Meshing surface 1 (Plane, Frontal-Delaunay)
Info    : Done meshing 2D (Wall 0.00200741s, CPU 0s)
Info    : 82 nodes 166 elements
Info    : Writing 'rectangle.msh'...
Info    : Done writing 'rectangle.msh'
.  use_python
this is x: 2.0
this is y: 3.0

```
Depending on how this could also be achieved we could then iterate on how the mesh generation step should be performed (i.e. if we could use the above python function or need something else).

**Comment by dglaeser** [comment]
> Writing to file and reading back in would not be an option?
I meant within one compute step to then afterwards pass it down "dynamically". CWL for instance has no means to access some value from within the python code. So we would have to write the value into some file, and then CWL allows to to export as output some value read from a file.

**Comment by pdiercks** [comment]
> I meant within one compute step to then afterwards pass it down "dynamically". CWL for instance has no means to access some value from within the python code

okay. I agree that we would not want to have the python constraint. Would it be possible to just write the value to stdout and capture that?

**Comment by dglaeser** [comment]
> I agree that we would not want to have the python constraint. Would it be possible to just write the value to stdout and capture that?

Probably, yes. I'd have to check how but I suppose it is possible. You'd prefer that because it is more representative for real scenarios in which a tool spits out something that is not simply the input that was given to it?

**Comment by dglaeser** [comment]
But I guess if that's the reason then we should make the gmsh step receive something different than just the size. For instance, make it receive some scaling parameter between 0 and 1 (for example), and then it internally maps that to some physical dimension which is returned at the end?

**Comment by pdiercks** [comment]
> You'd prefer that because it is more representative for real scenarios in which a tool spits out something that is not simply the input that was given to it?

No, I would be fine with returning the same value. But, it should be a "real" (non-file) output. 

> In the gmsh generation step we could have then simply added size as an input parameter, and simply pass that input parameter down to subsequent nodes as an output

This is totally fine. Sorry, I might have misunderstood that first.

**Comment by dglaeser** [comment]
yes, sounds good, thanks!
