### ISSUE TITLE
postprocessing.py: type object 'PlotOverLine' has no attribute 'Source'

### ISSUE THREAD

**Issue by onluen** [BAMresearch/NFDI4IngScientificWorkflowRequirements#54]
I get this error and a bunch of follow-up errors from paraview in `postprocessing.py`:

```
Traceback (most recent call last):
  File "/opt/paraview/lib/python3.10/site-packages/paraview/servermanager.py", line 476, in __setattr__
    setter = getattr(self.__class__, name)
AttributeError: type object 'PlotOverLine' has no attribute 'Source'
```

This happens with `paraview-5.10.1` from both archlinux and guix packages.

I see that paraview 5.9 something is listed in a conda yaml, but I don't find any mentioning of `Source` changes in the paraview changelogs.

I'm not familiar with paraview and don't know how to debug this issue. Maybe somebody with more experience has some ideas?

**Comment by pdiercks** [comment]
Hi @onluen ,

> I see that paraview 5.9 something is listed in a conda yaml, but I don't find any mentioning of Source changes in the paraview changelogs.

If possible you should use paraview version 5.9.1. We can discuss if we want to upgrade at some point.
I also didn't find any mentioning of `Source` changes in the paraview changelogs, but I can work on a version of `postprocessing.py` for paraview version 5.10.1 if we decide to upgrade.

**Comment by onluen** [comment]
Hey @pdiercks,

I just built `paraview-5.9.1` and now the example works: nice, thanks!

Supporting the current paraview release would be nice though, since I guess it's easier to upstream a current paraview package to guix.

Anyhow, this issue is fixed.
