### ISSUE TITLE
Incorporate GWL developer feedback regarding the simple use case implementation

### ISSUE THREAD

**Issue by pdiercks** [BAMresearch/NFDI4IngScientificWorkflowRequirements#61]
Hi @onluen ,

I am raising this issue here in order not to forget about this.

**Comment by joergfunger** [comment]
Isn't that already done?

**Comment by onluen** [comment]
No not yet, I still have to include the developer feedback into `simple_use_case/gwl/workflow.w`. I'm working on a fork right now, but it's not yet ready.

**Comment by pdiercks** [comment]
Hi @onluen , I am closing this issue since all the feedback from the GWL devs was incorporated.
