### ISSUE TITLE
GWL job fails

### ISSUE THREAD

**Issue by dglaeser** [BAMresearch/NFDI4IngScientificWorkflowRequirements#68]
@onluen, the GWL job in the actions has just failed (https://github.com/BAMresearch/NFDI4IngScientificWorkflowRequirements/actions/runs/3928719362/jobs/6716660134)

Any ideas what could be going wrong?

**Comment by onluen** [comment]
I think there was either a network hiccup or problems within in the guix infrastructure. This is from the CI log:

```
message: "some substitutes for the outputs of derivation `/gnu/store/vl1f6xp1zd2f131ggfy20v8lq5hkk7ji-libxext-1.3.4.drv' failed (usually happens due to networking issues)..."
```

I triggered a rebuild and everything seems fine again.

**Comment by dglaeser** [comment]
ok, thanks @onluen and sorry for bothering! I'll resolve this now
