### ISSUE TITLE
`run-gwl` fails because of bad gateway error

### ISSUE THREAD

**Issue by pdiercks** [BAMresearch/NFDI4IngScientificWorkflowRequirements#71]
the action to run the exemplary workflow with gwl fails because of a bad gateway error.
the download path in the [guix-install-action](https://github.com/PromyLOPh/guix-install-action/blob/v1/action.yml#L36) seems to be outdated.
we may need to open an issue in the guix-install-action repo.

**Comment by onluen** [comment]
Hi @pdiercks, the same link is also used on the guix nightly download page. I reached out in IRC and asked what to do.

**Comment by pdiercks** [comment]
Thanks!

**Comment by onluen** [comment]
Issue has been fixed upstream.
